version: '3'
tasks:
  build:
    desc: Build for current platform
    cmds:
      - go build -o bson2json ./cmd/bson2json
    sources:
      - cmd/bson2json/*.go
      - go.mod
      - go.sum
    generates:
      - bson2json

  build-all:
    desc: Build for all major platforms (linux, windows, macos, arm64/x86_64)
    cmds:
      - GOOS=linux   GOARCH=amd64   go build -o bin/bson2json-linux-amd64   ./cmd/bson2json
      - GOOS=linux   GOARCH=arm64   go build -o bin/bson2json-linux-arm64   ./cmd/bson2json
      - GOOS=darwin  GOARCH=amd64   go build -o bin/bson2json-macos-amd64   ./cmd/bson2json
      - GOOS=darwin  GOARCH=arm64   go build -o bin/bson2json-macos-arm64   ./cmd/bson2json
      - GOOS=windows GOARCH=amd64   go build -o bin/bson2json-windows-amd64.exe ./cmd/bson2json
      - GOOS=windows GOARCH=arm64   go build -o bin/bson2json-windows-arm64.exe ./cmd/bson2json
    sources:
      - cmd/bson2json/*.go
      - go.mod
      - go.sum
    generates:
      - bin/*

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf bson2json bin/
