name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build binary
        run: |
          ext=""
          if [ "${{ matrix.goos }}" = "windows" ]; then ext=".exe"; fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o bson2json-${{ matrix.goos }}-${{ matrix.goarch }}$ext ./cmd/bson2json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bson2json-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: bson2json-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
