name: Build, Tag, and Release

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/bson2json-linux-amd64 cmd/bson2json/main.go
          GOOS=darwin GOARCH=amd64 go build -o dist/bson2json-darwin-amd64 cmd/bson2json/main.go
          GOOS=windows GOARCH=amd64 go build -o dist/bson2json-windows-amd64.exe cmd/bson2json/main.go
          GOOS=linux GOARCH=arm64 go build -o dist/bson2json-linux-arm64 cmd/bson2json/main.go
          GOOS=darwin GOARCH=arm64 go build -o dist/bson2json-darwin-arm64 cmd/bson2json/main.go
          GOOS=windows GOARCH=arm64 go build -o dist/bson2json-windows-arm64.exe cmd/bson2json/main.go


      - name: Create/Push Tag
        id: tag_version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch   # Or 'minor', 'major', depending on your release strategy

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: bin/bson2json-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}